sentence = "The sum of 5 + 10 is {0}.".format(25)
print (sentence)
sentence = "The sum of 5 + 10 is {0}.".format(5+10)
print (sentence)
sentence = "The sum of {0} + {0} is {0}.".format(10)
print (sentence)
sentence = "The sum of {0} + {1} is {2}.".format(1,2,7)
print (sentence)
sentence = "The sum of {0} + {1} is {2}.".format(1,2,(1+2))
print (sentence)
sentence = "The sum of {0} + {1} is {2} and that's why we can't have nice things in Python.".format(1,"':)'",True)
print (sentence)
sentence = "The sum of {0} + {2} is {1}.".format(1,(1+2),2)
print (sentence)